version: '3'
services:
  csvserver:
    image: infracloudio/csvserver
    ports:
      - "9393:9300"
    volumes:
      - ./csvserver:/csvserver
    env_file:
      - csvserver.env
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - csvserver
